version: '2'
services:
  # rabbitmq:
  #   container_name: sgpc-rabbitmq
  #   image: 'rabbitmq:3.7-management-alpine'
  #   # restart: always
  #   ports:
  #     - '15672:15672'
  #     - '5672:5672'
  mongo:
    container_name: sgpc-mongo
    image: 'bitnami/mongodb:latest'
    # restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGODB_USERNAME=sgpc
      - MONGODB_PASSWORD=sgpc
      - MONGODB_DATABASE=sgpc
      - MONGODB_ROOT_PASSWORD=password123
    volumes:
      - 'mongodb_data:/bitnami'
  # mongo-express:
  #   container_name: sgpc-mongo-express
  #   image: mongo-express
  #   # restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password123
  # redis:
  #   container_name: sgpc-redis
  #   # restart: always
  #   image: 'bitnami/redis:latest'
  #   environment:
  #     - REDIS_PASSWORD=sgpc
  #     - ALLOW_EMPTY_PASSWORD=yes 
  #   ports:
  #     - '6379:6379'
  # postgres:
  #   image: postgres
  #   container_name: sgpc-postgres
  #   # restart: always
  #   environment:
  #     POSTGRES_DB: sgpc
  #     POSTGRES_USER: sgpc
  #     POSTGRES_PASSWORD: sgpc
  #   volumes:
  #     - ./assets/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mongodb_data:
    driver: local
